#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

#------------------------------------------------------------------------------

touch turbine_steady.foam

cd constant
#ln -s
#rm -r poly*
ln -s ../../mesh/domain/constant/polyMesh polyMesh
cd ..

restore0Dir

#runApplication mapFields /home/matheus/OpenFOAM/matheus-v2112/run/Horizontal_Turbines/turbine_cfMesh_working_Meshstudy_forwardNearWake_initialConditionsFix_components/steady -sourceTime latestTime -consistent

runApplication decomposePar #-force

# Run
#app=$(getApplication)
mpirun --oversubscribe -np 25 simpleFoam -parallel  > log.simpleFoam
#runApplication simpleFoam
# Reconstruct
runApplication reconstructPar

#------------------------------------------------------------------------------
